[variables]
  # এটি Playwright-কে নির্দেশ দেবে ব্রাউজারটি প্রজেক্ট ফোল্ডারে সেভ করতে
  PLAYWRIGHT_BROWSERS_PATH = "/app/pw-browsers"

[providers]
  nixpkgs = ["python3"]

[phases.setup]
  aptPkgs = ["tesseract-ocr"]

[phases.install]
  cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt",
    "python -m playwright install chromium --with-deps"
  ]

[phases.start]
  cmd = ". /opt/venv/bin/activate && python app.py"
